### ISSUE TITLE
'_RAND_bytes' not found

### ISSUE THREAD

**Issue by ericleasemorgan** [lyokato/p5-oauth-lite#9]
I don't know if submitting an issue here is apropos, but I'll try; I am unable to install OAuth-Lite on my Macintosh because of the following error:

Error:  Can't load '/System/Library/Perl/Extras/5.30/darwin-thread-multi-2level/auto/Crypt/OpenSSL/Random/Random.bundle' for module Crypt::OpenSSL::Random: dlopen(/System/Library/Perl/Extras/5.30/darwin-thread-multi-2level/auto/Crypt/OpenSSL/Random/Random.bundle, 0x0002): symbol '_RAND_bytes' not found, expected in flat namespace by '/System/Library/Perl/Extras/5.30/darwin-thread-multi-2level/auto/Crypt/OpenSSL/Random/Random.bundle' at /System/Library/Perl/5.30/XSLoader.pm line 96.

Is there some sort of work-around?

**Comment by lyokato** [comment]
this error says that Crypt::OpenSSL::Random installation failed, because it can't find OpenSSL library.
Make sure that you have OpenSSL on your machine, and it's header-path and library-path are included in your environment variables properly

**Comment by ericleasemorgan** [comment]
Thank you for the prompt reply. 

I have used Homebrew to reinstall OpenSSL:

  $ brew reinstall openssl@1.1

And then, as per the Homebrew's output, I updated my PATH as well as defined two more environment variables:

  $ export PATH="/opt/homebrew/opt/openssl@1.1/bin:$PATH"
  $ export LDFLAGS="-L/opt/homebrew/opt/openssl@1.1/lib"
  $ export CPPFLAGS="-I/opt/homebrew/opt/openssl@1.1/include"

But when I do perl Makefile.PL, make, and make test, I still get the same error. Have I not correctly made sure OpenSSL's header-path and library-path are included in my environment? Maybe I ought to edit makefile?

**Comment by lyokato** [comment]
https://metacpan.org/source/RURBAN/Crypt-OpenSSL-Random-0.15/Makefile.PL

Looking at Crypt::OpenSSL::Random's Makefile.PL,
It supports arguments INCDIR and LIBDIR to force to set your paths.
